name: Check Trigger

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install Dependencies
        run: python -m pip install -r monitoring-requirements.txt
      - name: Run Check Trigger Script
        run: python src/check_trigger.py ${{ github.event.inputs.csv }}
