name: Check Trigger

on:
  workflow_dispatch:
    inputs:
      csv:
        default: ""

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: monitoring-requirements.txt
      - name: Install Dependencies
        run: pip install -r monitoring-requirements.txt
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: shps
          path: data/
          if_no_artifact_found: warn
      - name: Run Check Trigger Script
        run: python src/update_trigger.py ${{ github.event.inputs.csv }}
        env:
          CHD_DS_EMAIL_USERNAME: ${{ secrets.CHD_DS_EMAIL_USERNAME }}
          CHD_DS_EMAIL_PASSWORD: ${{ secrets.CHD_DS_EMAIL_PASSWORD }}
          CHD_DS_HOST: ${{ secrets.CHD_DS_HOST }}
          CHD_DS_PORT: ${{ secrets.CHD_DS_PORT }}
      - uses: actions/upload-artifact@v3
        with:
          name: shps
          path: data/
